language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "igorbrehm-github" # the key of the org you chose at step #3
    token:
      secure: "3551c9d8c37f7fe71264d753bae0a3f902d8d690" # encrypted value of your token
script:
  - pytest
  - sonar-scanner
